// 180-day India day trading curriculum
export const CURRICULUM = [
  // PHASE 1: Foundations (Days 1–20)
  { day: 1, topic: "NSE & BSE Market Structure", phase: "Foundations", tags: ["NSE","BSE","SEBI"] },
  { day: 2, topic: "Order Types: Limit, Market, SL, SL-M", phase: "Foundations", tags: ["Orders","Execution"] },
  { day: 3, topic: "Bid-Ask Spread & Market Depth (Level 2)", phase: "Foundations", tags: ["Microstructure","Math"] },
  { day: 4, topic: "Circuit Breakers & SEBI Regulations", phase: "Foundations", tags: ["SEBI","Risk"] },
  { day: 5, topic: "Nifty 50 Index Construction & Weightage", phase: "Foundations", tags: ["Nifty","Index","Math"] },
  { day: 6, topic: "Sensex 30 Free-Float Market Cap Formula", phase: "Foundations", tags: ["Sensex","Math"] },
  { day: 7, topic: "India VIX: Formula & Interpretation", phase: "Foundations", tags: ["VIX","Volatility","Math"] },
  { day: 8, topic: "Intraday Margins: SPAN & Exposure", phase: "Foundations", tags: ["Margins","SEBI","Math"] },
  { day: 9, topic: "Brokerage, STT, GST: True Cost of a Trade", phase: "Foundations", tags: ["Costs","Math"] },
  { day: 10, topic: "Capital Gains Tax: STCG & LTCG for Traders", phase: "Foundations", tags: ["Tax","SEBI"] },
  { day: 11, topic: "Lot Sizes & Contract Value in F&O", phase: "Foundations", tags: ["F&O","NSE","Math"] },
  { day: 12, topic: "Settlement Cycles: T+1 vs T+2 on NSE", phase: "Foundations", tags: ["Settlement"] },
  { day: 13, topic: "Rolling Returns & CAGR Calculations", phase: "Foundations", tags: ["Math","Performance"] },
  { day: 14, topic: "Expectancy Formula for Trading Systems", phase: "Foundations", tags: ["Math","System"] },
  { day: 15, topic: "Log Returns vs Arithmetic Returns", phase: "Foundations", tags: ["Math","Returns"] },
  { day: 16, topic: "Normal Distribution & Z-Score in Prices", phase: "Foundations", tags: ["Statistics","Math"] },
  { day: 17, topic: "Annualizing Volatility: Daily σ → Annual σ", phase: "Foundations", tags: ["Volatility","Math"] },
  { day: 18, topic: "Correlation: Nifty Bank vs Nifty 50", phase: "Foundations", tags: ["Correlation","Math"] },
  { day: 19, topic: "Beta Calculation for Indian Stocks", phase: "Foundations", tags: ["Beta","Math"] },
  { day: 20, topic: "Sharpe Ratio with Indian Risk-Free Rate (G-Sec)", phase: "Foundations", tags: ["Sharpe","Math"] },

  // PHASE 2: Price Action (Days 21–40)
  { day: 21, topic: "Candlestick Anatomy: OHLC Mathematics", phase: "Price Action", tags: ["Candlestick","Math"] },
  { day: 22, topic: "Doji Patterns: Statistical Significance", phase: "Price Action", tags: ["Patterns","Statistics"] },
  { day: 23, topic: "Hammer & Shooting Star: Probability on Nifty", phase: "Price Action", tags: ["Patterns","Math"] },
  { day: 24, topic: "Engulfing Patterns: Win-Rate Backtests", phase: "Price Action", tags: ["Patterns","Backtest"] },
  { day: 25, topic: "Morning Star & Evening Star Logic", phase: "Price Action", tags: ["Patterns","3-candle"] },
  { day: 26, topic: "Marubozu & Body-to-Wick Ratio Formula", phase: "Price Action", tags: ["Patterns","Math"] },
  { day: 27, topic: "Inside Bar & NR7 Volatility Contraction", phase: "Price Action", tags: ["Volatility","Math"] },
  { day: 28, topic: "Heikin-Ashi Smoothing Formula", phase: "Price Action", tags: ["Heikin-Ashi","Math"] },
  { day: 29, topic: "Support & Resistance: Zone Width Math", phase: "Price Action", tags: ["S&R","Math"] },
  { day: 30, topic: "Pivot Points: Classic Formula (NSE EOD)", phase: "Price Action", tags: ["Pivots","Math"] },
  { day: 31, topic: "Fibonacci Retracements: Ratios & Levels", phase: "Price Action", tags: ["Fibonacci","Math"] },
  { day: 32, topic: "Fibonacci Extensions for Targets", phase: "Price Action", tags: ["Fibonacci","Math"] },
  { day: 33, topic: "Volume Profile: POC, VAH, VAL Calculations", phase: "Price Action", tags: ["Volume","Math"] },
  { day: 34, topic: "VWAP Formula & Intraday Mean Reversion", phase: "Price Action", tags: ["VWAP","Math"] },
  { day: 35, topic: "Opening Range Breakout (ORB) Statistics", phase: "Price Action", tags: ["ORB","Math"] },
  { day: 36, topic: "Gap Statistics on Nifty 50 (2010–2024)", phase: "Price Action", tags: ["Gaps","Statistics"] },
  { day: 37, topic: "Chart Patterns: Head & Shoulders Target Formula", phase: "Price Action", tags: ["Patterns","Math"] },
  { day: 38, topic: "Triangles: Measuring Breakout Targets", phase: "Price Action", tags: ["Patterns","Math"] },
  { day: 39, topic: "Flag & Pennant: Pole-Height Projection", phase: "Price Action", tags: ["Patterns","Math"] },
  { day: 40, topic: "Double Top/Bottom: Neckline Break Math", phase: "Price Action", tags: ["Patterns","Math"] },

  // PHASE 3: Indicators (Days 41–70)
  { day: 41, topic: "Simple Moving Average (SMA): Lag Analysis", phase: "Indicators", tags: ["SMA","Math"] },
  { day: 42, topic: "Exponential Moving Average (EMA): Smoothing Factor", phase: "Indicators", tags: ["EMA","Math"] },
  { day: 43, topic: "EMA vs SMA: Crossover Performance on BankNifty", phase: "Indicators", tags: ["EMA","SMA","Backtest"] },
  { day: 44, topic: "WMA & Hull MA: Reducing Lag Mathematically", phase: "Indicators", tags: ["HMA","Math"] },
  { day: 45, topic: "MACD: Full Derivation (12-26-9 EMA)", phase: "Indicators", tags: ["MACD","Math"] },
  { day: 46, topic: "MACD Histogram Divergence Detection", phase: "Indicators", tags: ["MACD","Divergence"] },
  { day: 47, topic: "RSI Formula: Wilder's Smoothing Method", phase: "Indicators", tags: ["RSI","Math"] },
  { day: 48, topic: "RSI Divergence on Nifty: Mathematical Definition", phase: "Indicators", tags: ["RSI","Divergence"] },
  { day: 49, topic: "Bollinger Bands: σ Calculation & Band Width", phase: "Indicators", tags: ["Bollinger","Math"] },
  { day: 50, topic: "Bollinger Band %B & Squeeze Formula", phase: "Indicators", tags: ["Bollinger","Math"] },
  { day: 51, topic: "ATR: True Range Definition & Wilder Avg", phase: "Indicators", tags: ["ATR","Math"] },
  { day: 52, topic: "ADX: +DI, -DI, DX, ADX Step-by-Step", phase: "Indicators", tags: ["ADX","Math"] },
  { day: 53, topic: "Parabolic SAR: Acceleration Factor Math", phase: "Indicators", tags: ["PSAR","Math"] },
  { day: 54, topic: "Stochastic Oscillator: %K & %D Formulas", phase: "Indicators", tags: ["Stochastic","Math"] },
  { day: 55, topic: "Williams %R vs Stochastic Relationship", phase: "Indicators", tags: ["Williams","Math"] },
  { day: 56, topic: "CCI (Commodity Channel Index): Mean Deviation", phase: "Indicators", tags: ["CCI","Math"] },
  { day: 57, topic: "OBV (On-Balance Volume) Cumulative Logic", phase: "Indicators", tags: ["OBV","Volume"] },
  { day: 58, topic: "Chaikin Money Flow Formula", phase: "Indicators", tags: ["CMF","Volume","Math"] },
  { day: 59, topic: "MFI (Money Flow Index): Volume-Weighted RSI", phase: "Indicators", tags: ["MFI","Math"] },
  { day: 60, topic: "Ichimoku Cloud: All 5 Line Formulas", phase: "Indicators", tags: ["Ichimoku","Math"] },
  { day: 61, topic: "Supertrend Indicator: ATR Multiplier Math", phase: "Indicators", tags: ["Supertrend","ATR","Math"] },
  { day: 62, topic: "Donchian Channels: Breakout System Math", phase: "Indicators", tags: ["Donchian","Math"] },
  { day: 63, topic: "Keltner Channels vs Bollinger Bands", phase: "Indicators", tags: ["Keltner","Math"] },
  { day: 64, topic: "Elder Ray: Bull & Bear Power Formulas", phase: "Indicators", tags: ["Elder","Math"] },
  { day: 65, topic: "TRIX: Triple-Smoothed EMA Rate of Change", phase: "Indicators", tags: ["TRIX","Math"] },
  { day: 66, topic: "Aroon Oscillator: Period-Based Math", phase: "Indicators", tags: ["Aroon","Math"] },
  { day: 67, topic: "Coppock Curve: Rate of Change Weighted Sum", phase: "Indicators", tags: ["Coppock","Math"] },
  { day: 68, topic: "Detrended Price Oscillator (DPO)", phase: "Indicators", tags: ["DPO","Math"] },
  { day: 69, topic: "Linear Regression Channel: Least Squares Formula", phase: "Indicators", tags: ["LinReg","Math"] },
  { day: 70, topic: "Combining Indicators: Reducing False Signals Mathematically", phase: "Indicators", tags: ["System","Math"] },

  // PHASE 4: Options F&O (Days 71–100)
  { day: 71, topic: "Options Basics: Call, Put, Premium on NSE", phase: "Options F&O", tags: ["Options","NSE"] },
  { day: 72, topic: "Intrinsic vs Time Value Decomposition", phase: "Options F&O", tags: ["Options","Math"] },
  { day: 73, topic: "Black-Scholes Model: Full Derivation", phase: "Options F&O", tags: ["BSM","Math"] },
  { day: 74, topic: "Delta (Δ): Hedge Ratio & Probability Proxy", phase: "Options F&O", tags: ["Greeks","Delta","Math"] },
  { day: 75, topic: "Gamma (Γ): Convexity & Delta Change Rate", phase: "Options F&O", tags: ["Greeks","Gamma","Math"] },
  { day: 76, topic: "Theta (Θ): Time Decay Formula & NSE Expiry", phase: "Options F&O", tags: ["Greeks","Theta","Math"] },
  { day: 77, topic: "Vega (ν): Premium Sensitivity to IV", phase: "Options F&O", tags: ["Greeks","Vega","Math"] },
  { day: 78, topic: "Rho (ρ): Interest Rate Sensitivity", phase: "Options F&O", tags: ["Greeks","Rho","Math"] },
  { day: 79, topic: "Implied Volatility: Newton-Raphson Extraction", phase: "Options F&O", tags: ["IV","Math"] },
  { day: 80, topic: "IV Percentile & IV Rank on Nifty Options", phase: "Options F&O", tags: ["IV","Statistics"] },
  { day: 81, topic: "Put-Call Parity: No-Arbitrage Formula", phase: "Options F&O", tags: ["PCR","Math"] },
  { day: 82, topic: "PCR (Put-Call Ratio) as Sentiment Indicator", phase: "Options F&O", tags: ["PCR","Sentiment"] },
  { day: 83, topic: "Max Pain Theory: Calculation on NSE Strikes", phase: "Options F&O", tags: ["MaxPain","Math"] },
  { day: 84, topic: "Covered Call Strategy: P&L Math", phase: "Options F&O", tags: ["Strategy","Math"] },
  { day: 85, topic: "Bull Call Spread: Breakeven & Max Profit Formula", phase: "Options F&O", tags: ["Spread","Math"] },
  { day: 86, topic: "Bear Put Spread: Net Debit Math", phase: "Options F&O", tags: ["Spread","Math"] },
  { day: 87, topic: "Long Straddle: Breakeven Distance Formula", phase: "Options F&O", tags: ["Straddle","Math"] },
  { day: 88, topic: "Short Strangle on Nifty Weekly: Premium Math", phase: "Options F&O", tags: ["Strangle","Math"] },
  { day: 89, topic: "Iron Condor: 4-Leg P&L Matrix", phase: "Options F&O", tags: ["IronCondor","Math"] },
  { day: 90, topic: "Butterfly Spread: Max Profit at Pinning Math", phase: "Options F&O", tags: ["Butterfly","Math"] },
  { day: 91, topic: "Futures Pricing: Cost of Carry Model (India)", phase: "Options F&O", tags: ["Futures","Math"] },
  { day: 92, topic: "Basis & Rollover: Futures vs Spot on NSE", phase: "Options F&O", tags: ["Futures","Basis"] },
  { day: 93, topic: "Open Interest Analysis: Change in OI Math", phase: "Options F&O", tags: ["OI","Math"] },
  { day: 94, topic: "Delta-Neutral Hedging: Shares Required Formula", phase: "Options F&O", tags: ["Hedging","Delta","Math"] },
  { day: 95, topic: "Gamma Scalping: P&L from Realized vs IV", phase: "Options F&O", tags: ["Gamma","Advanced"] },
  { day: 96, topic: "Theta Decay Curve: Non-Linear NSE Weekly", phase: "Options F&O", tags: ["Theta","Math"] },
  { day: 97, topic: "Vega Risk on Monthly vs Weekly Nifty Options", phase: "Options F&O", tags: ["Vega","NSE"] },
  { day: 98, topic: "Calendar Spread: Time Spread P&L Math", phase: "Options F&O", tags: ["Calendar","Math"] },
  { day: 99, topic: "Diagonal Spread: Rolling & Adjustment Math", phase: "Options F&O", tags: ["Diagonal","Math"] },
  { day: 100, topic: "Options Chain Reading: Strike Selection Math", phase: "Options F&O", tags: ["Chain","Math"] },

  // PHASE 5: Risk Mgmt (Days 101–130)
  { day: 101, topic: "Fixed Fractional Position Sizing Formula", phase: "Risk Mgmt", tags: ["PositionSizing","Math"] },
  { day: 102, topic: "Kelly Criterion: Optimal Bet Size Derivation", phase: "Risk Mgmt", tags: ["Kelly","Math"] },
  { day: 103, topic: "Half-Kelly & Fractional Kelly for Safety", phase: "Risk Mgmt", tags: ["Kelly","Math"] },
  { day: 104, topic: "R-Multiple System: Risk/Reward Accounting", phase: "Risk Mgmt", tags: ["R-Multiple","Math"] },
  { day: 105, topic: "Maximum Drawdown: Calculation & Recovery Math", phase: "Risk Mgmt", tags: ["Drawdown","Math"] },
  { day: 106, topic: "Calmar Ratio: Return-to-Drawdown Formula", phase: "Risk Mgmt", tags: ["Calmar","Math"] },
  { day: 107, topic: "Sortino Ratio: Downside Deviation Formula", phase: "Risk Mgmt", tags: ["Sortino","Math"] },
  { day: 108, topic: "Value at Risk (VaR): Parametric Method", phase: "Risk Mgmt", tags: ["VaR","Math"] },
  { day: 109, topic: "CVaR (Expected Shortfall) Formula", phase: "Risk Mgmt", tags: ["CVaR","Math"] },
  { day: 110, topic: "Monte Carlo Simulation for Trade Outcomes", phase: "Risk Mgmt", tags: ["MonteCarlo","Math"] },
  { day: 111, topic: "Ruin Probability Formula for Traders", phase: "Risk Mgmt", tags: ["Ruin","Math"] },
  { day: 112, topic: "Stop Loss Placement: ATR-Based Formula", phase: "Risk Mgmt", tags: ["StopLoss","ATR","Math"] },
  { day: 113, topic: "Trailing Stop: % vs ATR Mathematical Comparison", phase: "Risk Mgmt", tags: ["TrailingStop","Math"] },
  { day: 114, topic: "Portfolio Heat: Total Risk Across Positions", phase: "Risk Mgmt", tags: ["Portfolio","Math"] },
  { day: 115, topic: "Correlation-Adjusted Position Sizing", phase: "Risk Mgmt", tags: ["Correlation","Math"] },
  { day: 116, topic: "Consecutive Loss Sequence Probability", phase: "Risk Mgmt", tags: ["Probability","Math"] },
  { day: 117, topic: "Optimal f: Ralph Vince's Geometric Growth", phase: "Risk Mgmt", tags: ["OptimalF","Math"] },
  { day: 118, topic: "SEBI F&O Margin Rules: SPAN Computation", phase: "Risk Mgmt", tags: ["SEBI","SPAN","Math"] },
  { day: 119, topic: "Mark-to-Market (MTM) Loss on Futures", phase: "Risk Mgmt", tags: ["MTM","Futures"] },
  { day: 120, topic: "Risk-of-Ruin Table: Building Your Own", phase: "Risk Mgmt", tags: ["Ruin","Math"] },
  { day: 121, topic: "Psychological Capital: Sizing for Mental Edge", phase: "Risk Mgmt", tags: ["Psychology","Sizing"] },
  { day: 122, topic: "Daily Loss Limit: Scientific Setting Formula", phase: "Risk Mgmt", tags: ["DailyLimit","Math"] },
  { day: 123, topic: "Profit Factor Formula & Minimum Viable PF", phase: "Risk Mgmt", tags: ["ProfitFactor","Math"] },
  { day: 124, topic: "Trade Frequency & Time-to-Ruin Relationship", phase: "Risk Mgmt", tags: ["Frequency","Math"] },
  { day: 125, topic: "Ulcer Index: Sustained Drawdown Math", phase: "Risk Mgmt", tags: ["Ulcer","Math"] },
  { day: 126, topic: "Gain-to-Pain Ratio for Indian Traders", phase: "Risk Mgmt", tags: ["GPR","Math"] },
  { day: 127, topic: "Hedging Cost with Options on F&O Portfolio", phase: "Risk Mgmt", tags: ["Hedging","Math"] },
  { day: 128, topic: "Correlation Matrix: Nifty Sector ETFs", phase: "Risk Mgmt", tags: ["Correlation","ETF"] },
  { day: 129, topic: "Minimum Account Size for Various Strategies", phase: "Risk Mgmt", tags: ["Capital","Math"] },
  { day: 130, topic: "Post-Trade Analysis: Scoring Every Trade", phase: "Risk Mgmt", tags: ["Analysis","System"] },

  // PHASE 6: Strategies (Days 131–160)
  { day: 131, topic: "Trend Following: Breakout Entry Math on Nifty", phase: "Strategies", tags: ["Trend","Breakout"] },
  { day: 132, topic: "Mean Reversion: Z-Score Entry/Exit Rules", phase: "Strategies", tags: ["MeanReversion","Math"] },
  { day: 133, topic: "Momentum Factor: Cross-Sectional NSE Ranking", phase: "Strategies", tags: ["Momentum","Math"] },
  { day: 134, topic: "Statistical Arbitrage: Pairs Trading Math", phase: "Strategies", tags: ["PairsTrading","Math"] },
  { day: 135, topic: "Cointegration Test: Engle-Granger on Indian Stocks", phase: "Strategies", tags: ["Cointegration","Math"] },
  { day: 136, topic: "Intraday Gap & Go: Probability Statistics", phase: "Strategies", tags: ["Gap","Statistics"] },
  { day: 137, topic: "VWAP Bands Strategy: Deviation Levels", phase: "Strategies", tags: ["VWAP","Math"] },
  { day: 138, topic: "BankNifty Scalping: Tick Size Math", phase: "Strategies", tags: ["Scalping","BankNifty"] },
  { day: 139, topic: "Options Selling Math: Premium Decay Rate", phase: "Strategies", tags: ["Selling","Options"] },
  { day: 140, topic: "Strangle Adjustment Rules: Roll/Close Math", phase: "Strategies", tags: ["Adjustment","Math"] },
  { day: 141, topic: "Expiry Day Strategy: Pinning Effect Formula", phase: "Strategies", tags: ["Expiry","Math"] },
  { day: 142, topic: "Pre-Budget Rally Statistics (Indian Market)", phase: "Strategies", tags: ["Seasonality","Statistics"] },
  { day: 143, topic: "FII DII Flow Impact: Regression Analysis", phase: "Strategies", tags: ["FII","DII","Math"] },
  { day: 144, topic: "SGX Nifty / GIFT City Premium Math", phase: "Strategies", tags: ["SGX","Arbitrage"] },
  { day: 145, topic: "Index Rebalancing Trade: Anticipation Math", phase: "Strategies", tags: ["Rebalancing","Math"] },
  { day: 146, topic: "Event-Based Trading: Budget, RBI Policy Math", phase: "Strategies", tags: ["Events","Statistics"] },
  { day: 147, topic: "Time-of-Day Pattern Analysis (NSE Sessions)", phase: "Strategies", tags: ["Intraday","Statistics"] },
  { day: 148, topic: "Day-of-Week Effect on Nifty 50 (Data Study)", phase: "Strategies", tags: ["Seasonality","Statistics"] },
  { day: 149, topic: "Implied Move Formula for RBI/Budget Day", phase: "Strategies", tags: ["IV","Events","Math"] },
  { day: 150, topic: "Straddle on Events: Expected Move Formula", phase: "Strategies", tags: ["Straddle","Events","Math"] },
  { day: 151, topic: "Hedged Portfolio: Nifty Futures Short Math", phase: "Strategies", tags: ["Hedging","Futures"] },
  { day: 152, topic: "Synthetic Positions: Recreating with Options", phase: "Strategies", tags: ["Synthetic","Math"] },
  { day: 153, topic: "Cash-and-Carry Arbitrage on NSE Futures", phase: "Strategies", tags: ["Arbitrage","Math"] },
  { day: 154, topic: "ETF Arbitrage: Nifty BeES vs Spot Math", phase: "Strategies", tags: ["ETF","Arbitrage"] },
  { day: 155, topic: "Sector Rotation: Relative Strength Index Math", phase: "Strategies", tags: ["Sector","RS"] },
  { day: 156, topic: "52-Week High Breakout: Momentum Statistics", phase: "Strategies", tags: ["Breakout","Statistics"] },
  { day: 157, topic: "Results Season Strategy: IV Crush Math", phase: "Strategies", tags: ["Earnings","IV","Math"] },
  { day: 158, topic: "Rollover Analysis: Cost & Direction Signal", phase: "Strategies", tags: ["Rollover","Futures"] },
  { day: 159, topic: "Multi-Leg Payoff Diagram: Coding Your Own", phase: "Strategies", tags: ["Payoff","Math"] },
  { day: 160, topic: "System Design: Entry, Exit, Size, Filter Rules", phase: "Strategies", tags: ["System","Design"] },

  // PHASE 7: Quantitative (Days 161–180)
  { day: 161, topic: "Backtesting: Walk-Forward vs In-Sample Bias", phase: "Quantitative", tags: ["Backtest","Math"] },
  { day: 162, topic: "Overfitting: Degrees of Freedom in Strategy", phase: "Quantitative", tags: ["Overfitting","Math"] },
  { day: 163, topic: "Transaction Cost Modeling in Backtests", phase: "Quantitative", tags: ["Costs","Math"] },
  { day: 164, topic: "Slippage Estimation on NSE Liquid Stocks", phase: "Quantitative", tags: ["Slippage","Math"] },
  { day: 165, topic: "Monte Carlo on Trade Sequences: Confidence Bands", phase: "Quantitative", tags: ["MonteCarlo","Math"] },
  { day: 166, topic: "Bootstrap Resampling for Strategy Robustness", phase: "Quantitative", tags: ["Bootstrap","Math"] },
  { day: 167, topic: "Parameter Sensitivity: Heatmap Analysis", phase: "Quantitative", tags: ["Sensitivity","Math"] },
  { day: 168, topic: "Linear Regression on Nifty: Residual Analysis", phase: "Quantitative", tags: ["Regression","Math"] },
  { day: 169, topic: "Time Series: Autocorrelation on NSE Returns", phase: "Quantitative", tags: ["TimeSeries","Math"] },
  { day: 170, topic: "ARIMA Model: Fitting on Nifty Daily Data", phase: "Quantitative", tags: ["ARIMA","Math"] },
  { day: 171, topic: "GARCH Model: Volatility Clustering in NSE", phase: "Quantitative", tags: ["GARCH","Math"] },
  { day: 172, topic: "Machine Learning Basics: Features for Trading", phase: "Quantitative", tags: ["ML","Features"] },
  { day: 173, topic: "Random Forest Feature Importance for Signals", phase: "Quantitative", tags: ["ML","Math"] },
  { day: 174, topic: "Genetic Algorithms for Parameter Optimization", phase: "Quantitative", tags: ["GA","Optimization"] },
  { day: 175, topic: "Market Impact Model: Kyle's Lambda Formula", phase: "Quantitative", tags: ["MktImpact","Math"] },
  { day: 176, topic: "Execution Algorithms: TWAP & VWAP Math", phase: "Quantitative", tags: ["Execution","Algo"] },
  { day: 177, topic: "Order Flow Imbalance: Trade Arrival Models", phase: "Quantitative", tags: ["OrderFlow","Math"] },
  { day: 178, topic: "Building Your Trading Edge: Statistical Proof", phase: "Quantitative", tags: ["Edge","Statistics"] },
  { day: 179, topic: "Capital Allocation Across Multiple Strategies", phase: "Quantitative", tags: ["Allocation","Math"] },
  { day: 180, topic: "The Complete Trader: Integrating All 180 Days", phase: "Quantitative", tags: ["Synthesis","Final"] },
];

export const PHASE_COLORS = {
  "Foundations":   { bg: "#0d2137", accent: "#3b82f6", glow: "#1e40af" },
  "Price Action":  { bg: "#1a1a0d", accent: "#eab308", glow: "#854d0e" },
  "Indicators":    { bg: "#0d1f1a", accent: "#10b981", glow: "#065f46" },
  "Options F&O":   { bg: "#1f0d1f", accent: "#c084fc", glow: "#6b21a8" },
  "Risk Mgmt":     { bg: "#1f0d0d", accent: "#f87171", glow: "#7f1d1d" },
  "Strategies":    { bg: "#0d1f1f", accent: "#22d3ee", glow: "#0e7490" },
  "Quantitative":  { bg: "#1a1210", accent: "#fb923c", glow: "#7c2d12" },
};

export const PHASE_ORDER = [
  "Foundations","Price Action","Indicators","Options F&O","Risk Mgmt","Strategies","Quantitative"
];
